#+TITLE: Learn to use org-mode

First, watch this [[https://www.youtube.com/watch?v=fgizHHd7nOo][video in Youtube]] on why org-mode is so awesome. It will show you a lot of things that can be done with org-mode. Then, download this [[http://kitchingroup.cheme.cmu.edu/media/2014-07-12-Org-mode-is-awesome/why-org-mode.org][org file]], open it in Emacs, and try some of the things in the video.

The documentation at http://orgmode.org/org.html is pretty helpful if you like reading in a browser.

You can read the installed documentation by clicking on this link: info:org.

Note: This file is meant to be read in Emacs. Some parts of it won't work if you are reading it on GitHUB in a browser.

You may find other interesting org-mode videos on our [[https://www.youtube.com/channel/UCQp2VLAOlvq142YN3JO3y8w][YouTube Channel]].

* jmax
To use org-mode the way the Kitchin Group does, you will need to run jmax. You can get it at https://github.com/jkitchin/jmax.

Click this link: elisp:jmax-help to open the jmax manual.


* org-ref

Click this link: elisp:org-ref-help to open the org-ref manual.

See this [[https://www.youtube.com/watch?v=2t925KRBbFc][video]] on YouTube to see some examples of org-ref in action.
