#+TITLE: Kitchin Research Group

Welcome to the Kitchin Research group.

- [[./group-meetings-2015.org][Group meetings]]

* Your KitchinHUB repo
You should have a repo we will share at https://github.com/KitchinHUB/{your-andrewid}. This repo is predominantly for us to communicate files between you and me.

** Setup an ssh key for yourself and put it on github

Look in your ~/.ssh folder. If you see a file called id_rsa.pub copy the contents of that file to the clipboard. Go to https://github.com/settings/keys and click "New SSH key", give it a name, and paste the key in the field.

If you don't have an id_rsa.pub, Then run these commands:

#+BEGIN_SRC sh
cd ~/.ssh
ssh-keygen -t rsa -b 4096 -C "your_email@example.com"
#+END_SRC

Then do the instructions above to add it to github. This will make it easy to push and pull the repo.

** Clone your repo
Change to some directory where you want your repo to be and run this command:
#+BEGIN_SRC sh
git clone git@github.com/KitchinHUB/{your-andrewid}
#+END_SRC

I recommend you keep the number of places you clone the repo to a minimum because they need be synchronized.

** Using the repo
It is probably a good idea to "pull" your repo each time you start working on it to make sure you have the most up to date version.


* Resources
- [[./org-mode.org][Learn org-mode]]

- The Kitchin Group blog: http://kitchingroup.cheme.cmu.edu

- Check out this magit-tutorial: https://github.com/jkitchin/magit-tutorial
