#+LATEX_CLASS: cmu-article
#+LATEX_CLASS_OPTIONS: [12pt]
#+LATEX_HEADER: \usepackage{setspace}
#+LATEX_HEADER: \doublespacing
#+STARTUP: hideblocks

#+OPTIONS: toc:nil
#+TITLE: ZIRCONIA NEURAL
#+AUTHOR: Akshay Tharval

* Meeting 7/15
For initial calculations I took four structures of Zirconia, namely, cubic, tetragonal, orthorhombic and monoclinic. 
There were many structures available for each of the structure (except cubic) but I considered the structures with smallest volumes.
The structures were varied in their volumes from a factor of 0.85 to twice the size (but it varies according to the structures). Some structures with higher volume were varied only to 1.5 times its original size to avoid the case of non-convergence.
The structures were taken from [[https:materialsproject.com][Materials Project]]. 
The calculations were started with creating neural network for cubic Zirconia (the smallest and the most simplest structure)
** Calculations of Cubic
Calculations were done in [[*Calculations Cubic]] 
The structure along with its structure and specs were taken from [[https://materialsproject.org/materials/mp-1565/][Materials Project Cubic Structure]]
It is observed that 2 hidden layers should be enough to fit any function (while we use sigmoid as activation function)
Following are the results from various hierarchy tried 
| Hierarchy | Training RMSE    | Validation RMSE  |
|       5-5 | 0.92 meV/atom    | 0.33 meV/atom    |
|       6-6 | 0.9474 meV/atom  | 0.30603 meV/atom |
|       7-7 | 0.91882 meV/atom | 0.333 meV/atom   |
|       8-8 | 0.92779 meV.atom | 0.31663 meV/atom |
|     11-11 | 0.91905 meV/atom | 0.3312 meV/atom  |
|     12-12 | 0.9505 meV/atom  | 0.2806 meV/atom  |
|     13-13 | 0.9064 meV/atom  | 0.3521 meV/atom  |
|     14-14 | 0.9038 meV/atom  | 0.35078 meV/atom |
|     15-15 | 0.9023 meV/atom  | 0.3448 meV/atom  |
by general observation, we can see that as the number of hidden nodes increases, the RMSE value almost remains the same. Hence, we take the simplest structure into consideration (5-5).
** Calculations for combination of various structures
Next step was to include a few more structures available for calculations
[[https://materialsproject.org/materials/mp-754403/][Tetragonal Structure 1]]
[[https://materialsproject.org/materials/mp-2574/][Tetragonal Structure 2]]
[[https://materialsproject.org/materials/mp-775935/][Monoclinic Structure 1]] 
[[https://materialsproject.org/materials/mp-2858/][Monoclinic Structure 2]] 
[[https://materialsproject.org/materials/mp-776404/][Orthorhombic Structure 1]]
[[https://materialsproject.org/materials/mp-556605/][Orthorhombic Structure 2]] 
There were a few structures which did not converge even after multiple attempts (higher values like factor of 2). They were not considered for the building of data.
** Tetragonal 
Calculations were done for neural network with hidden nodes 2 to 30
| Hierarchy | Training RMSE   | Validation RMSE |
|     16-16 | 0.7339 meV/atom | 0.2879 meV/atom |
|     17-17 | 0.4997 meV/atom | 0.1940 meV/atom |
|     30-30 | 0.4765 meV/atom | 0.1428 meV/atom |

**  Monoclinic
Calculations still running
Completed calculations haven't given any converged structure

** Orthorhombic
calculations still running 
**  Combination of structures
The data was generated containing little under 400 entries [[*Combining the data]]
Still running the calculations for constructing a neural network for the combined data
The number of hidden nodes were ranged from 2 to 30 (2 hidden layers).

** GGA
GGA calculations are running now (till now the calculations were done using PBE). 
Further DFT calculations will be done using GGA (or PBE if advised otherwise)

** Vacancy for Bulk
As it was decided at the beginning of the project, this topic will be divided into two parts, vacancy in bulk (done by me) and vacancy on surface (done by Chen).
Vacancy calculations will be done using GGA (or PBE if advised otherwise)
Will start with single vacancy and further creating more.

** Next steps
- Document the neurals for Mono and Ortho (If the not the currently selected structures then other structures, calculations for those structures are done already)
- Neural for combined data and running it with Chen's model as well as running Chen's data with my model.
- Start documentation of project till date (as suggested by Prof. Kitchin)
- Learn and start using GITHUB more often.
- Extrapolate the neural (if 

** Issues faced
- When the neurals don't converge, the output file gives a suggestion of trying out the calculations again or to lower the goal error value.
- Have kept the neural calculations with lower goal error (2 meV/atom, default being 1meV/atom)
- Higher factors do not converge, so still considering whether to make an extra effort and calculate them (by putting a few more specs or by laxing a few specs)
